services:
  db:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'full_stack_app'
    command: postgres -c lc_monetary='en_US.UTF-8'
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
